//Samples to create tables for digital platform

  CREATE TABLE "KRISTIAN"."TABS" 
   (	"TABS_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"TABS" VARCHAR2(256 BYTE) NOT NULL ENABLE, 
	"TABS_ORDER" NUMBER(20,0) NOT NULL ENABLE, 
	"APPNAME" VARCHAR2(256 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "TABS_PK" PRIMARY KEY ("TABS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FIR"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FIR" ;

  
  
  
  
  
  CREATE TABLE "KRISTIAN"."ITEMS" 
   (	"ITEMS_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"ITEMS" VARCHAR2(256 BYTE) NOT NULL ENABLE, 
	"URL" VARCHAR2(4000 BYTE), 
	"ITEMS_ORDER" NUMBER(20,0) NOT NULL ENABLE, 
	"CONTENT" VARCHAR2(4000 BYTE), 
	"TABS_ID" NUMBER(20,0) NOT NULL ENABLE, 
	 CONSTRAINT "ITEMS_PK" PRIMARY KEY ("ITEMS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FIR"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FIR" ;

  
    CREATE TABLE "KRISTIAN"."TABS_TEST" 
   (	"TABS_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"TABS" VARCHAR2(256 BYTE) NOT NULL ENABLE, 
	"TABS_ORDER" NUMBER(20,0) NOT NULL ENABLE, 
	"APPNAME" VARCHAR2(256 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "TABS_TEST_PK" PRIMARY KEY ("TABS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FIR"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FIR" ;
  
  
  
  
  
    CREATE TABLE "KRISTIAN"."ITEMS_TEST" 
   (	"ITEMS_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"ITEMS" VARCHAR2(256 BYTE) NOT NULL ENABLE, 
	"URL" VARCHAR2(4000 BYTE), 
	"ITEMS_ORDER" NUMBER(20,0) NOT NULL ENABLE, 
	"CONTENT" VARCHAR2(4000 BYTE), 
	"TABS_ID" NUMBER(20,0) NOT NULL ENABLE, 
	 CONSTRAINT "ITEMS_TEST_PK" PRIMARY KEY ("ITEMS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FIR"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)